config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :workouts do
  resources :goals
end
  root 'workouts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
has_many :goals, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    @workout =  Workout.find(params[:workout_id])
    @goal = @workout.goals.create(params[:goal].permit(:name, :sets, :reps))

redirect_to workout_path(@workout)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]

 def index
  @workouts = Workout.all.order("created_at DESC")
  end

  def show
end

def  new
  @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :energy, :length)
    end
  def find_workout
    @workout = Workout.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/goals/_form.html.haml
= simple_form_for([@workout, @workout.goals.build]) do |l|
  = l.input :name, input_html: { class: "form-control" }
  = l.input :sets, input_html: { class: "form-control" }
  = l.input :reps, input_html: { class: "form-control" }
  %br/
  = l.button :submit

app/views/goals/_goal.html.haml
%p= goal.name
%p= goal.sets
%p= goal.reps

app/views/layouts/application.html.haml
!!!
%html
%head
  %title WorkOutBuddy</title>
  <link href="https://fonts.googleapis.com/css?family=Yatra+One" rel="stylesheet">

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-header
        = link_to "Workout Buddy", root_path, class: "navbar9 navbar-link"
      .nav.navbar-nav.navbar-right
        = link_to "Sports News",                  class:"navbar navbar-link"
        = link_to "Add a Workout", new_workout_path, class:"navbar navbar-link"
  .container
    = yield

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: {class: 'form-horizontal'}) do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :workout, label: "What kind of workout did you do?", input_html: {class: "form-control"} %>
  <%= f.input :energy, label: "How did you feel during your workout?", input_html: {class: "form-control"} %>
  <%= f.input :length, label: "Work out time?", input_html: {class: "form-control"} %>

  <%= f.button :submit %>

  <% end %>

app/views/workouts/edit.html.erb
<h1> Edit Your Workout</h2>

<%= render "form" %>

<%= link_to "cancel", root_path %>

app/views/workouts/index.html.haml
- @workouts.each do |workout|
  %h2= link_to workout.date, workout
  %h3= workout.workout

app/views/workouts/new.html.erb
<h1> Your New Workout </h1>

<%= render 'form' %>

<%= link_to "Didn't feel this Workout", root_path %>

app/views/workouts/show.html.haml
#workout

  %p= @workout.date
  %p= @workout.workout
  %p= @workout.energy
  %p= @workout.length

#goals
  %h2 Goals
  = render @workout.goals

  %h3 Add a new goal
  = render "goals/form"

  = link_to "Main Page", root_path |
  = link_to "Edit", edit_workout_path(@workout)
  =link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Not cool?" }